AttributeError: 'dict' object has no attribute 'extend' - Customization - Discuss Frappe/ERPNext
Try ERPNext
Try Frappe Cloud
Buy Support
Partners
Foundation
AttributeError: 'dict' object has no attribute 'extend'
Developers
Customization
arokia
October 9, 2019,
7:18am
#1
On fresh install erpnext am getting this traceback…
Screenshot%20from%202019-10-09%2013-04-491366×768 166 KB
hpema108
November 1, 2019, 12:56pm
#2
Hi @arokia
We having a similar error on bench update, so I suscpect someone release a fix that is braking something.
Kind regards
Hemant
Home
Categories
FAQ/Guidelines
Terms of Service
Privacy Policy
Powered by Discourse, best viewed with JavaScript enabled
Frappé Technologies Pvt Ltd, Mumbai